### ISSUE TITLE
Showing toast crashes app

### ISSUE THREAD

**Issue by rebootsramblings** [C-D-Lewis/ToastLayer#2]
I just added this library to my project to show some toasts (this is great by the way). When I show my toast, it animates in. When it reaches it's max point, it crashes the app. 

Currently building using SDK3 DP4.

Let me know if you need more details.

**Comment by C-D-Lewis** [comment]
Thanks for reporting this, it's due to the self-destroying animations in SDK 3.0. I'll add a conditional statement.

**Comment by rebootsramblings** [comment]
That's great. When I discovered this library in the community resources I air punched. Very cool.

**Comment by C-D-Lewis** [comment]
Try out the new master!

**Comment by rebootsramblings** [comment]
Works perfectly thanks. What did you end up changing (can't find the file comparison)? I want to adapt @gregoiresage 's project for the animated action bar to work as well. https://github.com/gregoiresage/pebble_animated_actionbar

**Comment by C-D-Lewis** [comment]
[This[(https://github.com/C-D-Lewis/ToastLayer/commit/4064f13adea3fd42d82f4bf000f8ed7381576c4b#diff-c4073b2fbc285bfe134c832fd6dd6506R27) is the crucial line change. I did a bunch of cleanup while I was in there.

**Comment by rebootsramblings** [comment]
That literally was the only thing I had to add. Going to create a pull request for @gregoirsage 's animated action bar repo. Thanks!
